# Generated by Django 6.1 on 2026-09-13 03:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('SMA', 'Sekolah Menengah Atas'), ('Kuliah', 'Kuliah')], max_length=20)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
