# Generated by Django 6.1 on 2026-09-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='experience_photos/'),
        ),
    ]
